type EndpointId = (id: string | number) => string

export const EP = {
  AUTH: {
    LOGIN:  '/auth/login',
    ME:     '/auth/me',
    LOGOUT: '/auth/logout',
  },
  EVENTOS: {
    LIST:       '/eventos',
    ONE:        ((id: string | number) => `/eventos/${id}`) as EndpointId,
    CREATE:     '/eventos',
    UPDATE:     ((id: string | number) => `/eventos/${id}`) as EndpointId,
    REMOVE:     ((id: string | number) => `/eventos/${id}`) as EndpointId,
    ATIVOS:     '/eventos/ativos',
  },
  TIPOS_EVENTO: {
    LIST:   '/tipos-evento',
    ONE:    ((id: string | number) => `/tipos-evento/${id}`) as EndpointId,
    CREATE: '/tipos-evento',
    UPDATE: ((id: string | number) => `/tipos-evento/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/tipos-evento/${id}`) as EndpointId,
  },
  PESSOAS: {
    LIST:   '/pessoas',
    ONE:    ((id: string | number) => `/pessoas/${id}`) as EndpointId,
    CREATE: '/pessoas',
    UPDATE: ((id: string | number) => `/pessoas/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/pessoas/${id}`) as EndpointId,
    SEARCH: '/pessoas/buscar',
  },
  PESSOAS_ENDERECOS: {
    LIST:   ((pessoaId: string | number) => `/enderecos/pessoas/${pessoaId}`) as EndpointId,
    ADD:    '/enderecos/pessoas',
    REMOVE: ((pessoaEnderecoId: string | number) => `/enderecos/pessoas/${pessoaEnderecoId}`) as EndpointId,
  },
  FAMILIAS: {
    LIST:   '/familias',
    ONE:    ((id: string | number) => `/familias/${id}`) as EndpointId,
    CREATE: '/familias',
    UPDATE: ((id: string | number) => `/familias/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/familias/${id}`) as EndpointId,
    SEARCH: '/familias/buscar',
  },
  PRESENCAS: {
    LIST:      '/presencas',
    ONE:       ((id: string | number) => `/presencas/${id}`) as EndpointId,
    CREATE:    '/presencas',
    UPDATE:    ((id: string | number) => `/presencas/${id}`) as EndpointId,
    REMOVE:    ((id: string | number) => `/presencas/${id}`) as EndpointId,
    BY_EVENTO: ((eventoId: string | number) => `/presencas/evento/${eventoId}`) as EndpointId,
    BY_PESSOA: ((pessoaId: string | number) => `/presencas/pessoa/${pessoaId}`) as EndpointId,
  },
  USUARIOS: {
    LIST:   '/usuarios',
    ONE:    ((id: string | number) => `/usuarios/${id}`) as EndpointId,
    CREATE: '/usuarios',
    UPDATE: ((id: string | number) => `/usuarios/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/usuarios/${id}`) as EndpointId,
  },
  CONFIG: {
    LIST: '/config',
    UPDATE: '/config',
  },
  TRADUCOES: {
    LIST:   '/traducoes',
    ONE:    ((id: string | number) => `/traducoes/${id}`) as EndpointId,
    CREATE: '/traducoes',
    UPDATE: ((id: string | number) => `/traducoes/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/traducoes/${id}`) as EndpointId,
  },
  VERSICULOS: {
    LIST:   '/versiculos',
    ONE:    ((id: string | number) => `/versiculos/${id}`) as EndpointId,
    CREATE: '/versiculos',
    UPDATE: ((id: string | number) => `/versiculos/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/versiculos/${id}`) as EndpointId,
  },
  UPLOAD: {
    IMAGEM:        '/upload/imagem',
    REMOVE_IMAGEM: ((nomeArquivo: string) => `/upload/imagem/${nomeArquivo}`) as EndpointId,
    LIST_IMAGENS:  '/upload/imagens',
  },
  IGREJAS: {
    LIST:   '/igrejas',
    ONE:    ((id: string | number) => `/igrejas/${id}`) as EndpointId,
    CREATE: '/igrejas',
    UPDATE: ((id: string | number) => `/igrejas/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/igrejas/${id}`) as EndpointId,
  },
  ENDERECOS: {
    LIST:   '/enderecos',
    ONE:    ((id: string | number) => `/enderecos/${id}`) as EndpointId,
    CREATE: '/enderecos',
    UPDATE: ((id: string | number) => `/enderecos/${id}`) as EndpointId,
    REMOVE: ((id: string | number) => `/enderecos/${id}`) as EndpointId,
  },
}
